---
- name: Set timezone to Europe/Amsterdam on CentOS
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Set the timezone to Europe/Amsterdam
      timezone:
        name: Europe/Amsterdam
