---
# Playbook to install updates on CentOS/RHEL servers
- name: Install updates on CentOS/RHEL servers
  hosts: test
  become: true
  become_method: sudo
  become_user: root
  tasks:
    # Task to update all packages to the latest version
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest
     # become: true
     # become_user: root
